### ISSUE TITLE
How to set domains and ranges for no-diagonal + no-upper or no-lower sploms?

### ISSUE THREAD

**Issue by etpinard** [dy/regl-scattermatrix#4]
Consider:

```js
const regl = require('regl')({ extensions: 'oes_element_index_uint' })
const createMatrix = require('./')

let splom = createMatrix(regl)

splom.update({
  data: [
    [1, 2, 3],
    [4, 6, 8],
    [1, 5, 9]
  ],
  ranges: [
    [0, 10],
    [0, 10],
    [0, 10]
  ],
  domain: [
    [0, 0, 0.3, 0.3],
    [0.35, 0.35, 0.65, 0.65],
    [0.7, 0.7, 1, 1] 
  ],
  diagonal: false,
  upper: false
})

splom.draw()
```

where `data`, `ranges` and `domains` have the same length - this generates:

![image](https://user-images.githubusercontent.com/6675409/38431452-39a714aa-3992-11e8-94f0-c7824f326fb1.png)

Now, if we want to just draw the three non-empty, how should we go about it? In this case, `data` should still be 3x3 both now there are only 2 x and 2 y axes.

**Comment by dy** [comment]
I expect adjusting the domain so
```js
```

**Comment by dy** [comment]
Domain should be adjusted accordingly, similar to
```js
  domain: [
    [0, 0, 0.5, null],
    [0.5, 0, 1, 0.5],
    [null, 0.5, 1, 1]
  ],
```
I can make `adjustDiagonal` option to do that.

**Comment by dy** [comment]
Ok, off https://github.com/dy/regl-scattermatrix/commit/83b350dc048e2032a8a6cdd88a5448c0992af09b there is `adjustDiag` option to correct domain to hidden elements. It should be aligned with paddings though.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/2505/commits/7f916b09780a45b0825f7d9af907a516f606d44e
