### ISSUE TITLE
destroy is broken again

### ISSUE THREAD

**Issue by etpinard** [dy/regl-scattermatrix#5]
from any splom mock off https://github.com/plotly/plotly.js/pull/2505 then calling `Plotly.purge(gd)` (which calls `splom.destroy`) gives:

![image](https://user-images.githubusercontent.com/6675409/38433515-26e8a05c-3999-11e8-88df-01189a8acaa5.png)

![image](https://user-images.githubusercontent.com/6675409/38433523-2c68bf58-3999-11e8-8a4d-9f810901ff45.png)

**Comment by dy** [comment]
Fixed in https://github.com/dy/regl-scatter2d/commit/d60bfa765eb385717e7b1ba5833be44810e44ca9

**Comment by etpinard** [comment]
thanks for fix!
