### ISSUE TITLE
No 'marker' option?

### ISSUE THREAD

**Issue by etpinard** [dy/regl-scattermatrix#6]
SDF markers (as in regl-scatter2d) don't seem to be supported.

**Comment by dy** [comment]
Whoops, fixed e66a02be922ff167b0d3b72ecb725c6adccf22f7 thanks!

**Comment by etpinard** [comment]
![image](https://user-images.githubusercontent.com/6675409/38586022-f83f4266-3ce9-11e8-9aa7-0f89b9cc33a7.png)

Looking great! Thanks :tada:
